const allCampaigns = [
      {
        id: "ravi-transplant",
        name: "Ravi's Liver Transplant",
        location: "Apollo Hospital, Hyderabad",
        story: "Ravi, a 34-year-old schoolteacher and father of two, requires an urgent liver transplant within 18 days. His family has exhausted all personal savings.",
        raised: 820000,
        goal: 1500000,
        donors: 412,
        daysLeft: 18,
        category: "Transplant",
        urgentBadge: "Urgent",
        hospital: "Apollo Hospital, HYD",
        image: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=600&h=400&fit=crop",
        alt: "Medical team preparing for a liver transplant"
      },
      {
        id: "priya-daughter-surgery",
        name: "Help Priya's Daughter Ananya",
        location: "AIIMS, New Delhi",
        story: "Ananya, 6 years old, was born with congenital heart disease and requires open-heart surgery next week. Every single day counts to save her little heart.",
        raised: 420000,
        goal: 800000,
        donors: 847,
        daysLeft: 12,
        category: "Surgery",
        urgentBadge: "Critical",
        hospital: "AIIMS, New Delhi",
        image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=600&h=400&fit=crop",
        alt: "Pediatric heart-care team examining a young patient"
      },
      {
        id: "arjun-cancer-treatment",
        name: "Arjun's Cancer Treatment",
        location: "Tata Memorial Hospital, Mumbai",
        story: "Six grueling cycles of chemotherapy ahead for 24-year-old engineering graduate Arjun fighting acute lymphoblastic leukemia. Join his fight.",
        raised: 1150000,
        goal: 2000000,
        donors: 1203,
        daysLeft: 45,
        category: "Cancer",
        urgentBadge: "Tax 80G",
        hospital: "Tata Memorial, Mumbai",
        image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop",
        alt: "Patient receiving cancer treatment in a clinical setting"
      },
      {
        id: "suresh-icu-emergency",
        name: "Emergency ICU Care for Suresh",
        location: "Manipal Hospital, Bengaluru",
        story: "A severe highway collision left Suresh in critical neuro-trauma ICU care with ventilator support. His wife is asking for community support tonight.",
        raised: 95000,
        goal: 350000,
        donors: 156,
        daysLeft: 5,
        category: "Emergency",
        urgentBadge: "Critical",
        hospital: "Manipal Hospital, BLR",
        image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&h=400&fit=crop",
        alt: "Critical-care equipment in an intensive care unit"
      },
      {
        id: "aarvi-bone-marrow",
        name: "Baby Aarvi's Bone Marrow Transplant",
        location: "Fortis Memorial, Gurugram",
        story: "3-year-old Aarvi is battling severe aplastic anemia. Her sister is a 100% matching donor, but the transplant and sterile isolation room costs ₹25 Lakhs.",
        raised: 1840000,
        goal: 2500000,
        donors: 1480,
        daysLeft: 14,
        category: "Pediatric",
        urgentBadge: "Urgent Match Found",
        hospital: "Fortis Hospital, NCR",
        image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&h=400&fit=crop",
        alt: "Young child representing Aarvi during her bone marrow treatment"
      },
      {
        id: "lakshmi-kidney-replacement",
        name: "Lakshmi's Kidney Replacement",
        location: "CMC Vellore, Tamil Nadu",
        story: "Mother of three Lakshmi suffers from chronic end-stage kidney failure. Tri-weekly dialysis is no longer sustainable. A renal transplant is her only hope.",
        raised: 530000,
        goal: 1200000,
        donors: 580,
        daysLeft: 22,
        category: "Transplant",
        urgentBadge: "Critical",
        hospital: "CMC Vellore",
        image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&h=400&fit=crop",
        alt: "Patient receiving kidney care from a medical professional"
      },
      {
        id: "twin-nicu-babies",
        name: "Emergency NICU Care for Preemie Twins",
        location: "Rainbow Children's Hospital, Hyderabad",
        story: "Born prematurely at 27 weeks weighing just 850 grams each, the baby twins need prolonged incubator support and respiratory care to survive.",
        raised: 740000,
        goal: 1100000,
        donors: 690,
        daysLeft: 9,
        category: "Pediatric",
        urgentBadge: "Urgent",
        hospital: "Rainbow Hospital, HYD",
        image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&h=400&fit=crop",
        alt: "Premature newborn receiving neonatal care in an incubator"
      },
      {
        id: "meena-breast-cancer",
        name: "Meena's Targeted Immunotherapy",
        location: "HCG Cancer Centre, Bengaluru",
        story: "Stage 3 HER2+ breast cancer requires targeted antibody infusions every 3 weeks. Meena is a single mother determined to watch her teenage son graduate.",
        raised: 680000,
        goal: 950000,
        donors: 730,
        daysLeft: 30,
        category: "Cancer",
        urgentBadge: "Tax 80G",
        hospital: "HCG Cancer Centre",
        image: "https://images.unsplash.com/photo-1579684453423-f84349ef60b0?w=600&h=400&fit=crop",
        alt: "Patient receiving breast cancer immunotherapy"
      },
      {
        id: "kiran-accident-recovery",
        name: "Kiran's Road Accident Recovery",
        location: "Narayana Health, Bengaluru",
        story: "Kiran, a 29-year-old delivery rider, needs multiple orthopedic surgeries and rehabilitation after a road accident. His family is raising funds to help him recover and return home.",
        raised: 285000,
        goal: 900000,
        donors: 214,
        daysLeft: 26,
        category: "Emergency",
        urgentBadge: "Urgent",
        hospital: "Narayana Health, BLR",
        image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=600&h=400&fit=crop",
        alt: "Orthopedic team caring for a patient after an accident"
      },
      {
        id: "farah-cataract-surgery",
        name: "Farah's Cataract Surgery",
        location: "LV Prasad Eye Institute, Hyderabad",
        story: "Farah is a 61-year-old tailor whose vision has been clouded by cataracts. Surgery on both eyes will help her regain her independence and return to work.",
        raised: 76000,
        goal: 180000,
        donors: 97,
        daysLeft: 38,
        category: "Surgery",
        urgentBadge: "Needs Support",
        hospital: "LV Prasad Eye Institute, HYD",
        image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop",
        alt: "Ophthalmologist examining a patient's eyes"
      },
      {
        id: "dev-diabetes-treatment",
        name: "Dev's Diabetes Complication Care",
        location: "KEM Hospital, Pune",
        story: "Dev, a 16-year-old student, needs specialist treatment and ongoing care for serious diabetes complications. His parents are seeking help with the medical costs so he can focus on recovery and school.",
        raised: 132000,
        goal: 500000,
        donors: 168,
        daysLeft: 33,
        category: "Treatment",
        urgentBadge: "Ongoing Care",
        hospital: "KEM Hospital, Pune",
        image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&h=400&fit=crop",
        alt: "Doctor checking a young patient's diabetes care plan"
      },
      {
        id: "geeta-burns-treatment",
        name: "Geeta's Burn Injury Treatment",
        location: "Safdarjung Hospital, New Delhi",
        story: "Geeta sustained severe burns in a kitchen accident and needs reconstructive procedures, wound care, and time in hospital. Her family is asking for support during a difficult recovery.",
        raised: 194000,
        goal: 750000,
        donors: 243,
        daysLeft: 21,
        category: "Emergency",
        urgentBadge: "Critical",
        hospital: "Safdarjung Hospital, Delhi",
        image: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=600&h=400&fit=crop",
        alt: "Burn-care specialist treating a patient in hospital"
      }
    ];
